const mongoose = require("mongoose");

const playerSchema = new mongoose.Schema(
  {
    tourney_id: String,
    tourney_name: String,
    surface: String,
    draw_size: Number,
    tourney_level: String,
    tourney_date: Number,
    match_num: Number,
    winner_id: Number,
    winner_seed: Number,
    winner_entry: String,
    winner_name: String,
    winner_hand: String,
    winner_ht: Number,
    winner_ioc: String,
    winner_age: Number,
    loser_id: Number,
    loser_seed: Number,
    loser_entry: String,
    loser_name: String,
    loser_hand: String,
    loser_ht: Number,
    loser_ioc: String,
    loser_age: Number,
    score: String,
    best_of: Number,
    round: Number,
    minutes: Number,
    w_ace: Number,
    w_svpt: Number,
    w_1stIn: Number,
    w_1stWon: Number,
    w_2ndWon: Number,
    w_bpSaved: Number,
    w_bpFaced: Number,
    l_ace: Number,
    l_df: Number,
    l_svpt: Number,
    l_1stIn: Number,
    l_1stWon: Number,
    l_2ndWon: Number,
    l_SvGms: Number,
    l_bpSaved: Number,
    l_bpFaced: Number,
    winner_rank: Number,
    winner_rank_points: Number,
    loser_rank: Number,
    loser_rank_points: Number,
    winner_local_id: String,
    loser_local_id: String,
    winner_elo: Number,
    loser_elo: Number,
    winner_elo_surface: Number,
    loser_elo_surface: Number,
    winner_elo_gains: Number,
    loser_elo_gains: Number,
    winner_elo_surface_gains: Number,
    loser_elo_surface_gains: Number,
  },
  { collection: "matches" }
);

module.exports = mongoose.model("matches", playerSchema);
